// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
config({ path: ".env.local" });
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use the session-mode pooler (port 5432) or direct connection URL from Supabase.
    // Supabase: Settings → Database → Connection string → Session mode
    url: process.env["DATABASE_URL"],
  },
});
